# Generated by Django 5.2.1 on 2025-06-11 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdf_uploads/')),
                ('total_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list, help_text='List of tags associated with the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('vector_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pdf_rag.pdfdocument')),
            ],
            options={
                'ordering': ['document', 'page_number', 'chunk_index'],
            },
        ),
    ]
