# Generated by Django 5.2.1 on 2025-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='tags',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='pdf_rag.tag'),
        ),
    ]
